### ISSUE TITLE
Image Preview Broken For Multiple Images

### ISSUE THREAD

**Issue by MisansProducts** [LancersBucket/plugin-RemoveChatButtons#1]
When more than 1 image is attached to a message and sent in any channel, the plugin causes the preview to show nothing after you click on it.

I believe the class in question is called `visualMediaItemContainer` when it creates anything other than `oneByOneGrid` class elements.

Here is an example:
![Example Image Gallery View](https://github.com/user-attachments/assets/79e660b0-7aed-4691-8fb7-21af66fbaf58)

Here is what it should normally look like (PLUGIN DISABLED):
![Plugin Disabled](https://github.com/user-attachments/assets/df390150-4f1d-4f8b-a1a3-21e1ff45ae9a)

And this is what it actually looks like (PLUGIN ENABLED):
![Discord_quYaFidjZm](https://github.com/user-attachments/assets/fbc9fc4f-48c4-4222-af36-31bf569a73ef)

Attached is my config file for issue replication.
[RemoveChatButtons.config.json](https://github.com/user-attachments/files/16776194/RemoveChatButtons.config.json)

EDIT: I'm using branch patch-2, but this was also an issue I had on main for a while.

**Comment by LancersBucket** [comment]
This issue was fixed by in @jlortiz0 in https://github.com/BleedingBD/plugin-RemoveChatButtons/pull/21 so I went ahead and added their changes to this repo. The fix can be found on the main branch at https://github.com/LancersBucket/plugin-RemoveChatButtons/commit/cfec894969457f75f594b045cf4cfeb9dfe86f32. I merged patch-2 into main so you won't be missing any of the fixes/features I've added.

**Comment by MisansProducts** [comment]
Thank you!
